-- Vtipy o slepicích – seed data pro tabulku text_snippets
-- Typ: joke

INSERT INTO text_snippets (type, content) VALUES
('joke', 'Proč slepice přešla přes cestu? Aby se dostala na druhou stranu. Proč kohout přešel přes cestu? Aby dokázal, že není zbabělec.'),
('joke', 'Přijde slepice do knihovny a říká: „Buk, buk, buk." Knihovnice jí dá tři knihy. Slepice odejde. Druhý den přijde znovu: „Buk, buk, buk." Dostane další tři knihy. Knihovnice ji tajně sleduje. Slepice dojde k rybníku a podá knihy žábě. Žába se podívá a říká: „Čte-la, čte-la, čte-la…"'),
('joke', 'Co dělá slepice, když stojí na jedné noze? Zvedne tu druhou.'),
('joke', 'Jaký je rozdíl mezi slepicí a rybou? Oba plavou. Kromě slepice.'),
('joke', 'Malý Pepíček se ptá farmáře: „Proč ta slepice běhá dokola?" – „Protože jí teče do oka."'),
('joke', 'Potká se slepice s koněm. Slepice říká: „Já dávám vejce." Kůň na to: „A já zase koně."'),
('joke', 'Co je to: sedí na zemi, je to žluté a píská? Kuřátko na poplach.'),
('joke', 'Učitelka se ptá Pepíčka: „Kolik nohou má slepice?" – „Dvě." – „A kolik nohou má kráva?" – „Čtyři." – „A kolik nohou má pavouk?" – „Paní učitelko, vy nemáte doma žádná zvířata?"'),
('joke', 'Dvě slepice stojí u plotu. Jedna říká: „Kdák, kdák!" Druhá na to: „To jsem taky chtěla říct!"'),
('joke', 'Proč slepice sedí na vejcích? Protože kdyby si na ně stoupla, rozbila by je.'),
('joke', 'Co řekne slepice, když snese čtvercové vejce? „Auvajs!"'),
('joke', 'Kohout najde pštrosí vejce a donese ho do kurníku. „Nechci vás kritizovat," říká slepicím, „ale podívejte se, co dělá konkurence!"'),
('joke', 'Proč nesmí slepice do letadla? Protože by pořád chtěla kdákat z okna.'),
('joke', 'Farmář říká sousedovi: „Moje slepice snášejí tak velká vejce, že se na ně musí dívat zezhora." – „Proč?" – „Protože ze strany to vypadá jako balón."'),
('joke', 'Co je to: běhá po dvoře a má to na sobě pruhovaný svetr? Slepice v zimě.'),
('joke', 'Přijde slepice k doktorovi. „Pane doktore, bolí mě v kříži." – „Nesete vejce?" – „Ne, jsem tu pěšky."'),
('joke', 'Jaký je rozdíl mezi slepicí a klavírem? Klavír nemůžete oškubat.'),
('joke', 'Proč kohout kokrhá se zavřenýma očima? Protože to umí zpaměti.'),
('joke', 'Co dělá slepice na fotbalovém hřišti? Dává penalty. Z voleje.'),
('joke', 'Slepice říká kohoutovi: „Přestaň kokrhat, sousedi si stěžujou!" Kohout: „Ať si koupí špunty!"'),
('joke', 'Malá holčička se ptá babičky: „Babi, proč ta slepice tak divně chodí?" – „To je kachna, zlatíčko."'),
('joke', 'Co je to: je to kulaté, bílé a létá to? Vejce, když ho slepice špatně namíří.'),
('joke', 'Dva farmáři se hádají. Jeden říká: „Moje slepice snášejí vejce každý den!" Druhý: „To nic, moje snášejí vejce s nápisem „čerstvé"."'),
('joke', 'Proč slepice nikdy nevyhraje v pokeru? Protože vždycky ukáže, co má v ruce… tedy v křídle.'),
('joke', 'Co řekne slepice na Silvestra? „Šťastný nový rok, ať se vám dobře snáší!"'),
('joke', 'Slepice přišla do hospody a objednala si pivo. Hospodský: „Promiňte, ale slepice neobsluhujeme." Slepice: „To je diskriminace! Zavolám na drůbežářskou inspekci!"'),
('joke', 'Jaký je rozdíl mezi slepicí a manželkou? Slepice nejdřív kdáká a pak snese vejce. Manželka nejdřív vejce snese a pak kdáká.'),
('joke', 'Farmář říká veterináři: „Moje slepice nesnášejí vejce." – „A co nesnášejí?" – „Jedna druhou."'),
('joke', 'Proč slepice nepoužívají internet? Příliš mnoho spamu v e-mailu. A navíc se bojí cookies.'),
('joke', 'Co dělají dvě slepice, když se potkají? Kdákají o počasí a ceně zrní.'),
('joke', 'Pepíček říká mamince: „Mami, naše slepice snesla vejce!" – „To je hezké." – „A pak ho zase zvedla."'),
('joke', 'Ptáček si sedne na plot vedle slepice a říká: „Já umím lítat!" Slepice na to: „No a? Já umím dělat snídani."'),
('joke', 'Jak se jmenuje slepice, co snáší vejce na střeše? Nebezpečná.'),
('joke', 'Co řekne slepice ráno? „Už zase vstávat? Já bych radši zůstala v hnízdě."'),
('joke', 'Farmář se chlubí: „Mám slepici, která umí počítat." – „To není možné!" – „Je! Pokaždé, když snesu vejce, řekne: Jedno!"'),
('joke', 'Proč kohout nosí korunku? Protože je král kurníku.'),
('joke', 'Co je horší než najít červa v jablku? Být slepice a nenajít žádného.'),
('joke', 'Dvě slepice se baví. Jedna říká: „Slyšela jsi? Farmářka kupuje inkubátor!" Druhá: „Skvělé, konečně volno!"'),
('joke', 'Co říká slepice před spaním? „Dobrou noc, a ať se vám zdá o červech."'),
('joke', 'Jaký je rozdíl mezi slepicí a pštrosem? Asi 80 kilo a metr a půl.'),
('joke', 'Slepice říká kachně: „Ty umíš plavat, lítat i chodit po zemi. Jsi univerzální." Kachna: „Jo, ale nic z toho pořádně."'),
('joke', 'Farmář přijde do obchodu: „Potřebuju krmivo pro slepice." – „Granulované?" – „Ne, celé slepice."'),
('joke', 'Proč slepice nechodí do posilovny? Protože už mají dost velká stehna.'),
('joke', 'Co dělá slepice v dešti? Mokne.'),
('joke', 'Malý Pepíček napsal slohovou práci: „Naše slepice snese každý den jedno vejce. Tatínek je snese na trh. A tam je snese kupec."'),
('joke', 'Přijde kohout za slepicí a říká: „Podívej, co jsem našel – pštrosí vejce!" Slepice: „To není výzva, to je vyhrožování."'),
('joke', 'Proč slepice přeběhla přes silnici dvakrát? Protože je dvojitý agent.'),
('joke', 'Co řekne farmář slepicím ráno? „Tak holky, jaký bude dnešní výkon?"'),
('joke', 'Slepice sedí na hnízdě a kohout přinese velikonoční vajíčko. „Podívej se, co dělají v cizině!" říká.'),
('joke', 'Jak poznáte šťastnou slepici? Snáší vajíčka s úsměvem. Tedy… skořápka se tak tváří.'),
('joke', 'Dva kohouti se potkají. „Jak se máš?" – „Kokrhám." – „A kromě práce?"'),
('joke', 'Proč slepice neběhají maraton? Protože po pěti kilometrech by z nich byl rosol.'),
('joke', 'Farmář říká ženě: „Koupil jsem novou slepici!" – „A kde ji máš?" – „Běží za mnou, ale pomalu – nemá kondičku."'),
('joke', 'Co řekne slepice, když najde zlaté vejce? „Kdo mi sem dal ten kýč?"'),
('joke', 'Jaký sport dělají slepice? Kdákros.'),
('joke', 'Slepice říká kohoutovi: „Kdyby sis koupil hodinky, nemusel bys kokrhat podle slunce." Kohout: „Kdyby sis koupila kalendář, věděla bys, že je neděle!"'),
('joke', 'Co dělá slepice, když má hlad? Jde do bufetu. Tedy... na dvůr.'),
('joke', 'Proč kohout nikdy neprohraje hádku? Protože má vždycky poslední slovo – kokrhá nejdřív.'),
('joke', 'Farmář volá veterináři: „Moje slepice kokrhá!" – „To je kohout." – „Ne, říkám vám, je to slepice – včera snesla vejce!"'),
('joke', 'Co je společného mezi slepicí a matematikem? Oba počítají s vejci.'),
('joke', 'Slepice říká kočce: „Já dávám lidem snídani." Kočka: „Já dávám lidem alergii."'),
('joke', 'Malý Tomáš se ptá dědy: „Dědo, proč ta slepice hrabě v zemi?" – „Hledá červy." – „A proč je nezavolá?"'),
('joke', 'Přijde slepice k lékaři: „Pane doktore, mám problém – každý den snesu vejce, ale nikdo mi neděkuje."'),
('joke', 'Proč slepice nehrají šachy? Protože se bojí, že budou obětovány jako pěšci.'),
('joke', 'Co říká kohout, když zapomene kokrhnout? „Sorry, zaspal jsem. Stane se i nejlepším."'),
('joke', 'Dvě slepice se baví u plotu. „Ty máš ale pěkné peří!" – „Díky, je nové. Právě jsem přepeřila."'),
('joke', 'Proč nosí slepice peří? Protože kožich by jim byl velký.'),
('joke', 'Farmář říká: „Mám nejchytřejší slepici na světě." – „Co umí?" – „Pokaždé, když snesu vejce… tedy, když ONÁ snese vejce… ehm…"'),
('joke', 'Co dělá slepice na internetu? Surfuje na stránkách o zrní.'),
('joke', 'Jaký je rozdíl mezi slepicí a baseballovým hráčem? Oba umí chytat, ale slepice chytá červy.'),
('joke', 'Slepice přijde do banky: „Chtěla bych si otevřít účet." – „Dobře, kolik chcete vložit?" – „Tři vejce."'),
('joke', 'Kohout říká slepici: „Proč jsi smutná?" – „Protože mě lidi pořád srovnávají s kuřetem z KFC."'),
('joke', 'Proč slepice chodí na trh? Aby zjistila svoji tržní hodnotu.'),
('joke', 'Co si myslí slepice, když vidí omeletu? „To mohl být někdo z nás…"'),
('joke', 'Slepice a kráva se hádají, kdo je důležitější. Slepice: „Já dávám vejce na snídani!" Kráva: „Já dávám mléko na snídani!" Prase se ozve: „Já dávám na snídani všechno!"'),
('joke', 'Farmář za úplňku otevře kurník a slepice kokrhá. „To je vlkoslepice!" křičí.'),
('joke', 'Co řekne slepice, když se jí narodí kuřátko? „Konečně někdo, kdo mě chápe."'),
('joke', 'Proč slepice nepíšou dopisy? Protože mají špatný rukopis. Tedy… drápopis.'),
('joke', 'Ptáčátko se ptá slepice: „Proč nelétáš?" Slepice: „Mám příliš plný kalendář na zemi."'),
('joke', 'Jaký je oblíbený film slepic? Jurský park. Koneckonců, jsou příbuzné s dinosaury.'),
('joke', 'Kohout přijde domů pozdě. Slepice: „Kde jsi byl?!" – „Na kokrhací soutěži." – „A vyhrál jsi?" – „Ne, přišel jsem pozdě, než jsem zakokrhal."'),
('joke', 'Co dělá slepice v knihovně? Hledá recept na... ne, počkejte, to by bylo morbidní.'),
('joke', 'Slepice říká husám: „Vy máte ale dlouhé krky!" Husy: „Alespoň vidíme, odkud přichází farmář s nožem."'),
('joke', 'Jak pozná farmář, že slepice je chytrá? Snese vejce přímo do krabičky.'),
('joke', 'Proč slepice nepoužívají navigaci? Protože vždycky najdou cestu zpátky do kurníku.'),
('joke', 'Co řekl kohout, když poprvé uviděl páva? „Kamaráde, to ses ale vytáhl!"'),
('joke', 'Slepice říká kohoutovi: „Hele, farmář kupuje nového kohouta." – „Cože? To je převrat! To je puč!"'),
('joke', 'Proč jsou slepice tak dobré v matematice? Protože pořád počítají svá vejce.'),
('joke', 'Co dělá slepice v noci? Sní o velkých červech a malých liškách.'),
('joke', 'Farmář pojmenoval svoji slepici Einstein. Protože každé vejce, co snese, je geniální.'),
('joke', 'Pepíček: „Tati, co bylo dřív – slepice, nebo vejce?" – „Dřív byl oběd, ale teď je krize, tak máme jenom vejce."'),
('joke', 'Jak slepice slaví narozeniny? Dají si dort s červy navrch.'),
('joke', 'Slepice přijde do kina. „Jeden lístek, prosím." – „Na jaký film?" – „Na Kuře melancholik."'),
('joke', 'Proč kohout nenosí kalhoty? Protože by neměl kam dát ocas.'),
('joke', 'Co říká slepice, když vidí lišku? „Děvčata, evakuace! Tohle není cvičení!"'),
('joke', 'Farmář koupil slepicím televizi. Teď nesnášejí vejce, ale reality show.'),
('joke', 'Proč se slepice nikdy nehádají s kohoutem? Protože by stejně měl poslední zakokrhání.'),
('joke', 'Co je to, když slepice snese vajíčko na kopci? Převalí se.'),
('joke', 'Slepice říká kohoutovi: „Pojď, jdeme na procházku!" – „Ne, musím zůstat. Za hodinu kokrhám."'),
('joke', 'Jaký je oblíbený tanec slepic? Fox-trot. Tedy… fox ne, to je nebezpečné. Kdák-trot!'),
('joke', 'Co si slepice říkají na Vánoce? „Aspoň že na štědrovečerní tabuli je kapr, a ne my."'),
('joke', 'Farmář říká: „Moje slepice snášejí bio vejce." – „Jak to?" – „Krmím je ekologickým zrním a pouštím jim relaxační hudbu."'),
('joke', 'Proč slepice nikdy nelžou? Protože pravda vždycky vykvokne.'),
('joke', 'Co dělá slepice, když je horko? Snáší vejce natvrdo.'),
('joke', 'Jedna slepice říká druhé: „Četla jsi tu novou kuchařku?" – „Jo. Hrůza. Strana 42 – recept na kuře!"'),
('joke', 'Proč slepice nechodí k zubaři? Protože nemají zuby. Ale zobák jim taky nikdo nespravuje.'),
('joke', 'Sousedka se ptá farmářky: „Kolik vajec snese vaše slepice za den?" – „Jedno." – „To je málo." – „Pro slepici je to tak akorát."'),
('joke', 'Kohout říká: „Já jsem tady šéf!" Slepice: „Tak proč ty nesnášíš vejce?"'),
('joke', 'Co je to kuřecí filozofie? „Snáším, tedy jsem."'),
('joke', 'Farmář přinesl slepicím nový bidýlko. Slepice: „Konečně upgrade! Verze 2.0."'),
('joke', 'Proč slepice nechodí do školy? Protože už umí všechno, co potřebují – hrabat a kdákat.'),
('joke', 'Co řekne kohout ráno? „Kikirikí!" Co řekne farmář? „Drž hubu, je pět ráno!"'),
('joke', 'Slepice řekla kohoutovi: „Ty jsi jako budík – spolehlivý, ale otravný."'),
('joke', 'Proč slepice nekouří? Protože udírna je jejich noční můra.'),
('joke', 'Jaký je rozdíl mezi kuřecím stehnem a matematickým testem? Z kuřecího stehna mají lidi radost.'),
('joke', 'Farmář říká veterináři: „Jedna slepice mi nese dvě vejce denně." – „Výborně!" – „Ale ta druhá mi nese nulu." – „Tak tu vyhoďte." – „Ale ta první nese jen proto, že závodí s druhou!"'),
('joke', 'Co dělá slepice na pláži? Hrabe v písku, jako všude jinde.'),
('joke', 'Slepice se ptá kohouta: „Miluješ mě?" Kohout: „A kdepak bych jinde kokrhal?"'),
('joke', 'Přijde kuřátko za mámou: „Mami, je mi zima!" – „Běž do kurníku." – „Tam je mi taky zima!" – „Tak si dej peří!"'),
('joke', 'Jaký je rozdíl mezi optimistickou a pesimistickou slepicí? Optimistka snáší vejce a doufá, že z nich bude kuřátko. Pesimistka snáší vejce a bojí se omelety.'),
('joke', 'Proč slepice nepoužívají výtah? Protože jim stačí jen pár schodů na bidýlko.'),
('joke', 'Co dělá slepice na dovolené? To samé co doma – hrabe, kdáká a snáší vejce. Ale u moře.'),
('joke', 'Farmář koupil slepicím rádio. Jejich oblíbená stanice? Kokrhací vlna.'),
('joke', 'Proč kohout přeběhl přes cestu a zpátky? Protože zapomněl, proč přeběhl poprvé.'),
('joke', 'Slepice říká kachně: „Ty se umíš vznést nad vodu." Kachna: „A ty se umíš vznést nad snídani celého národa."'),
('joke', 'Co říká slepice při stěhování? „Hlavně nezapomeňte hnízdo!"'),
('joke', 'Farmář chce naučit slepice třídit odpad. Slepice: „My už třídíme – zrní nalevo, červy napravo."'),
('joke', 'Proč kohout nemá rád zimu? Protože mu mrzne hřebínek.'),
('joke', 'Co řekne slepice, když vidí vejce v obchodě za 5 korun? „To je urážka mé práce!"'),
('joke', 'Dvě slepice na bidýlku. Jedna: „Co budeš dělat zítra?" Druhá: „To co vždycky – snůška, zrní, spánek. Ty?" – „To samé. Žijeme snem."'),
('joke', 'Proč slepice neřídí auto? Protože by pořád zastavovaly u každého červa na silnici.'),
('joke', 'Farmář říká slepicím: „Kdo dnes snese nejvíc vajec, dostane odměnu!" Slepice se podívají na sebe: „A co za odměnu?" – „Nebudete na večeři."'),
('joke', 'Jaký je oblíbený sport kohoutů? Box. Mají to v krvi.'),
('joke', 'Slepice přijde k sousedce: „Nemáte trochu mouky? Peču dort." – „Slepice peče dort?" – „Co je na tom divného? Vejce mám svoje."'),
('joke', 'Proč slepice nechodí na ryby? Protože červy si nechávají pro sebe.'),
('joke', 'Co si slepice dává pod stromeček? Nové hnízdo a teplou podestýlku.'),
('joke', 'Farmář říká: „Mám slepici, která umí mluvit!" – „Co říká?" – „Kdák." – „To mluví každá slepice." – „Ale tahle to myslí vážně."'),
('joke', 'Kohout se ptá slepice: „Kolik dnes?" – „Jedno." – „Včera byla dvě." – „Včera jsem měla motivaci."'),
('joke', 'Co dělá slepice, když prší? Stojí pod přístřeškem a nadává na počasí, jako všichni ostatní.'),
('joke', 'Slepice říká kohoutovi: „Ty máš krásný hřebínek." Kohout: „Díky, je to rodové."'),
('joke', 'Proč se slepicím říká drůbež a ne hrůběž? Protože jsou docela milé. Většinou.'),
('joke', 'Co dělá slepice na ledě? Klouže. A pak kdáká, že je to nebezpečné.'),
('joke', 'Malá holčička: „Mami, ta slepice se na mě divně dívá!" – „To proto, že jíš vajíčko."'),
('joke', 'Slepice říká praseti: „Ty a já, dáváme lidem snídani." Prase: „Ty dáváš příspěvek. Já dávám závazek."'),
('joke', 'Proč slepice nepotřebují GPS? Protože se vždycky vrátí do kurníku před setměním.'),
('joke', 'Co řekne farmář, když najde vejce v botě? „Zase ta slepice improvizuje."'),
('joke', 'Dvě slepice v kurníku. Jedna kýchne. Druhá: „Na zdraví!" První: „Díky. Snad to není ptačí chřipka."'),
('joke', 'Proč kohout stojí na jedné noze? Protože kdyby zvedl obě, spadl by.'),
('joke', 'Slepice říká farmáři: „Dneska žádné vejce." Farmář: „Proč?" Slepice: „Je neděle. Mám nárok na volno."'),
('joke', 'Co je nejoblíbenější jídlo slepic? Cokoliv, co najdou na zemi.'),
('joke', 'Farmář se ptá slepice: „Proč snášíš vejce v garáži?" – „V kurníku je obsazeno."'),
('joke', 'Jak se jmenuje kohout, co běhá po dvoře pozpátku? Zmatený.'),
('joke', 'Slepice zaklepe na dveře farmáře: „Promiňte, ale v kurníku je myš." Farmář: „A?" Slepice: „A já se bojím!"'),
('joke', 'Proč jsou slepice špatné v karetních hrách? Protože se jim třesou křídla, když blafují.'),
('joke', 'Co řekne slepice, když najde diamant? Nic, myslí si, že je to lesklé zrnko.'),
('joke', 'Kohout ráno zakokrhá. Slepice: „Proboha, je teprve čtyři!" Kohout: „Sorry, předběhl jsem dobu."'),
('joke', 'Farmář říká: „Moje slepice jsou jako zaměstnanci – ráno přijdou, odvedou práci a pak se flákají."'),
('joke', 'Proč slepice nepoužívají sociální sítě? Protože by měly příliš mnoho followerů. A všichni by chtěli vejce.'),
('joke', 'Co je společného mezi slepicí a počítačem? Oboje má čip. Tedy… slepice na něj alespoň reaguje, když je ze zrní.'),
('joke', 'Slepice se ptá kohouta: „Kam jdeš?" – „Na bidýlko." – „Ale je teprve poledne." – „Mám noční směnu."'),
('joke', 'Proč slepice nerady cestují? Protože je v kurníku všechno, co potřebují.'),
('joke', 'Co řekne slepice jestřábovi? „… !" Nic neřekne, utíká.'),
('joke', 'Farmář koupil slepicím houpačku. Teď se houpou místo snášení vajec. „Investice se nevrátila," mumlá farmář.'),
('joke', 'Proč slepice nepíšou deník? Protože by tam každý den bylo: „Snesla jsem vejce. Jedla jsem zrní. Šla jsem spát."'),
('joke', 'Kohout říká slepici: „Nezlob se, ale trochu jsi přibrala." Slepice: „To není tuk, to je peří!"'),
('joke', 'Jak se slepice připravuje na zimu? Nejde. Farmář jí dá slámu a tím to hasne.'),
('joke', 'Pepíček: „Tati, naše slepice utekla!" – „Kam?" – „K sousedům. Prej tam mají lepší zrní."'),
('joke', 'Dvě kuřátka se baví. „Kde je máma?" – „Snáší vejce." – „Furt pracuje, co?"'),
('joke', 'Slepice přijde ke studni a podívá se dolů. „Kdo jsi?" ptá se svého odrazu. Odraz: „Kdák." Slepice: „Jsme příbuzné!"'),
('joke', 'Co dělá slepice, když je smutná? Jde do kouta kurníku a kdáká tiše.'),
('joke', 'Proč farmář mluví se slepicemi? Protože slepice se nehádají.'),
('joke', 'Slepice říká kohoutovi: „Pojď, zkusíme crossfit." Kohout: „Co je to?" Slepice: „Přeběhneš dvůr a zpátky." Kohout: „To dělám každý den!"'),
('joke', 'Přijde slepice do restaurace. Číšník: „Co si dáte?" Slepice: „Rozhodně ne kuřecí."'),
('joke', 'Farmář nainstaloval kameru do kurníku. Slepice teď mají svoji reality show: „Kurník Big Brother."'),
('joke', 'Proč kohout nepotřebuje budík? Protože JE budík.'),
('joke', 'Co řekne kuřátko, když poprvé vidí sníh? „Kdo vypnul trávu?"'),
('joke', 'Slepice říká kočce: „Nech mě na pokoji!" Kočka: „Klid, jsem na dietě. Dneska jen myši."'),
('joke', 'Proč slepice nenosí hodinky? Protože čas měří podle kohouta.'),
('joke', 'Farmář: „Musím slepicím pustit muziku, prej pak lépe snášejí." Žena: „A co jim pustíš?" – „Heavy metal. Ať snášejí tvrdá vejce."'),
('joke', 'Co dělá slepice, když se nudí? Počítá zrníčka na zemi.'),
('joke', 'Kohout říká: „Já jsem tu nejdůležitější!" Slepice: „Tak zkus snést vejce."'),
('joke', 'Dva farmáři se baví: „Kolik máš slepic?" – „Dvacet." – „A kolik vajec denně?" – „Záleží na náladě. Slepic, ne mojí."'),
('joke', 'Proč slepice rády hrabou? Protože hledají smysl života. A červy.'),
('joke', 'Slepice říká: „Kdybych uměla lítat, letěla bych na Kanáry." Kohout: „Tam jsou kočky." Slepice: „Zůstanu v kurníku."'),
('joke', 'Co řekne slepice svému vejci? „Měj se hezky, ať z tebe bude cokoliv."'),
('joke', 'Farmář namaloval kurník na růžovo. Slepice: „No, aspoň je to originální."'),
('joke', 'Proč se slepice bojí kuchyně? Protože tam všechno končí špatně.'),
('joke', 'Přijde kohout do baru a říká: „Jedno pivo!" – „Kohoutkové?" – „Takhle blbý vtipy nemám rád."'),
('joke', 'Slepice říká farmáři: „Chci dovolenou." Farmář: „Kde?" Slepice: „Kdekoliv, kde mě nikdo nechce sníst."'),
('joke', 'Co dělá slepice v deset večer? Spí. Slepice mají rozumný režim.'),
('joke', 'Malý Tomáš: „Mami, slepice mi sebrala svačinu!" Máma: „Jakou svačinu?" Tomáš: „Rohlík se zrním."'),
('joke', 'Proč slepice neberou úvěry? Protože nemají stabilní příjem. Jen vejce.'),
('joke', 'Co je nejhorší práce na farmě? Říkat slepicím, že je čas na polévku.'),
('joke', 'Slepice říká kachně: „Proč máš tak ploché nohy?" Kachna: „A proč ty máš tak špičatý zobák?" Obě: „Touché."'),
('joke', 'Farmář říká ženě: „Slepice mi rozklovali záhon!" Žena: „Měl jsi tam nedávat kukuřici."'),
('joke', 'Kohout se chlubí: „Mám harem!" Slepice: „Má kurník. A uklízí ho farmář."'),
('joke', 'Proč slepice nesedí na vejcích jiných slepic? Protože mají svůj vlastní projekt.'),
('joke', 'Přijde slepice do lékárny: „Dáte mi něco na peří?" Lékárník: „Šampón?" Slepice: „Ne, lepidlo. Padá mi."'),
('joke', 'Co dělá slepice na horách? Hledá alpské červy.'),
('joke', 'Farmář dal slepicím puzzle. Za týden ho složily. Obraz kurníku.'),
('joke', 'Proč slepice neplavou? Protože by jim plavky nesedly.'),
('joke', 'Slepice říká svému kuřátku: „Jednou budeš velká slepice a budeš snášet vejce." Kuřátko: „A co když budu kohout?" Slepice: „Pak budeš vstávat ve čtyři ráno."'),
('joke', 'Co je to – žluté, kulaté a pořád se kutálí? Vejce na šikmé ploše.'),
('joke', 'Farmář přijde do kurníku a najde slepice, jak hrají karty. „Co to děláte?!" Slepice: „Poker. Vsázíme vejce."'),
('joke', 'Proč slepice nesnáší nedělní obědy? Z pochopitelných důvodů.'),
('joke', 'Co je společného mezi slepicí a detektivem? Obě hledají stopy. Slepice ale hledají ty od červů.'),
('joke', 'Slepice říká psovi: „Ty střežíš dům, já živím farmáře. Kdo je tu důležitější?" Pes: „Já. Tebe může nahradit obchod."'),
('joke', 'Farmář pojmenoval slepice po dnech v týdnu. V neděli má volno – ta slepice nesnáší.'),
('joke', 'Proč kuřátka chodí do školy? Aby se naučila, jak přejít cestu.'),
('joke', 'Co řekl farmář, když slepice snesla trojitý žloutek? „Jackpot!"'),
('joke', 'Kohout říká: „Ráno vstanu, zakokrhám a celá farma vstane." Slepice: „To není talent, to je otrava."'),
('joke', 'Proč mají slepice křídla? Aby mohly mávat na rozloučenou vejcím.'),
('joke', 'Co dělá slepice na Silvestra? Kdáká odpočítávání. Kdák… kdák… kdák… KIKIRIKI!'),
('joke', 'Farmář čte slepicím z kuchařky. Slepice utečou. „Nějak neocenily literaturu," říká.'),
('joke', 'Proč slepice nejedí čokoládu? Protože by měly výčitky svědomí z kalorií. Ne, vlastně ne – slepice výčitky nemají.'),
('joke', 'Slepice říká farmáři: „Chci klimatizaci v kurníku!" Farmář: „Máš peří, to je tvoje klimatizace."'),
('joke', 'Co řekne slepice veterináři? „Doktore, mám pocit, že ze mě lezou blechy." – „To je normální." – „Normální? Já jsem slepice, ne pes!"'),
('joke', 'Dva kohouti se perou. Slepice sedí u plotu a komentují: „Ten vpravo má lepší techniku." – „Ale ten vlevo má hezčí hřebínek."'),
('joke', 'Proč slepice nepoužívají kalkulačku? Protože preferují přirozený počet – jedna slepice, jedno vejce.'),
('joke', 'Farmář říká: „Slepice jsou jako ráno – každý den přijdou, ať chceš nebo ne."'),
('joke', 'Přijde slepice na poštu: „Chci poslat vejce." – „Křehké?" – „Samozřejmě! Co myslíte, že snáším – cihly?"'),
('joke', 'Co dělá slepice na střeše? Hraje si na anténu.'),
('joke', 'Kohout říká: „Vím, co bude k obědu." Slepice: „Co?" Kohout: „Záleží na tom, jak rychle utečeš."'),
('joke', 'Proč slepice nerady létají? Protože ekonomická třída je pod jejich úroveň a na business nemají.'),
('joke', 'Farmářova žena: „Slepice snesla vejce ve vaně!" Farmář: „Aspoň je čisté."'),
('joke', 'Co říká slepice, když přijde jaro? „Konečně červi! Čerství červi!"'),
('joke', 'Proč kohout zakokrhá na plotě? Protože tam má nejlepší výhled a akustiku.'),
('joke', 'Slepice říká: „Já jsem jako automat na vejce, akorát potřebuju zrní místo mincí."'),
('joke', 'Malý Honzík se ptá: „Mami, proč se tomu říká kuřecí polévka a ne slepičí?" Máma: „Protože slepice se na to téma nerady baví."'),
('joke', 'Farmář říká: „Mám slepici, co snáší vejce podle objednávky." – „Jak to?" – „Řeknu jí datum, a ona ho snese." – „To nedává smysl." – „Slepicím máloco dává smysl."'),
('joke', 'Co dělá kohout v dešti? Kokrhá mokře.'),
('joke', 'Slepice na farmě svolá poradu: „Kolegyně, musíme zvýšit produktivitu!" Ostatní: „Dobře, ale chceme lepší zrní a delší přestávky."'),
('joke', 'Proč slepice přeběhla přes hřiště? Rozhodčí odpískal faul na druhé straně.'),
('joke', 'Přijde farmář do kurníku a vidí slepice, jak sedí v kruhu. „Co děláte?" – „Skupinovou terapii. Téma: strach z polévky."'),
('joke', 'Co říká slepice, když snesu malé vejce? „Dneska jsem měla kreativní blok."'),
('joke', 'Kohout se učí hrát na kytaru. Slepice: „Přestaň!" Kohout: „Proč?" Slepice: „Stačí nám tvoje ranní kokrhání."'),
('joke', 'Proč slepice nepíšou básně? Protože jejich rýmy jsou vždy: kdák – kdák – kdák – kdák.'),
('joke', 'Co dělá slepice, když uvidí duhu? Přemýšlí, jestli na konci je hrnec se zrním.'),
('joke', 'Farmář: „Proč snášíš vejce za šifonérem?" Slepice: „Hledala jsem soukromí."'),
('joke', 'Dvě slepice na bidýlku. Jedna spadne. „Jsi v pořádku?" – „Jo, přistála jsem na měkko. Na podestýlku."'),
('joke', 'Proč slepice obdivují kohouta? Kvůli hřebínku. Je to jako účes, ale navždy.'),
('joke', 'Co říká farmář slepicím každý večer? „Dobrou noc, holky. Zítra jedeme znova."'),
('joke', 'Slepice přijde za kohoutem: „Mám pro tebe překvapení!" Kohout: „Vejce?" Slepice: „…jak jsi to věděl?"'),
('joke', 'Proč slepice milují podzim? Protože listí na zemi vypadá jako obrovská podestýlka.'),
('joke', 'Co je nejčastější věta na farmě? „Kde ta slepice zase nese?"'),
('joke', 'Farmář říká veterináři: „Moje slepice zpívají." – „To je neobvyklé." – „Hlavně falešně."'),
('joke', 'Proč se slepice vždycky vrátí domů? Protože venku je nebezpečno a v kurníku je pohoda.'),
('joke', 'Přijde slepice k automechanikovi: „Můj motor nefunguje." Mechanik: „Vy nemáte motor." Slepice: „Tak proto nejedu!"'),
('joke', 'Co dělá kohout, když prší? Kokrhá pod střechou. Profesionál za každého počasí.'),
('joke', 'Farmář dal slepicím jmenovky. Teď se hádají, kdo má hezčí jméno.'),
('joke', 'Proč slepice nehledají poklad? Protože jim stačí najít červa.'),
('joke', 'Slepice filosofuje: „Co je smysl života?" Kohout: „Kokrhání za úsvitu." Slepice: „Tak to jsem ráda, že jsem slepice."'),
('joke', 'Co je to kuřecí diplomacie? Když dvě slepice chtějí stejné hnízdo a vyřeší to bez kdákání.'),
('joke', 'Farmář: „Moje slepice nesnášejí vejce." Soused: „Máte kohouta?" Farmář: „Ano, ale on taky nesnáší vejce."'),
('joke', 'Proč je v kurníku vždycky veselo? Protože slepice mají vejce-lentní náladu.'),
('joke', 'Co řekne slepice na konci dne? „Zase jsem to zvládla. Ráno znova."');
